packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@biomejs/biome": ^1.9.4
  "@types/node": ^20.17.5
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8
  next: ^15.0.2
  "@next/bundle-analyzer": ^15.0.2

catalogs:
  react19:
    react: 19.0.0-rc-02c0e824-20241028
    react-dom: 19.0.0-rc-02c0e824-20241028
    babel-plugin-react-compiler: 19.0.0-beta-63b359f-20241101
    "@types/react": npm:types-react@rc
    "@types/react-dom": npm:types-react-dom@rc